apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: skala-practice
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1OcnQ5UWFFSXpKUVRTMDZfTEZ1eW5GQ2h5V2NEZlNwWlhaZmJtYjFnd0ZHekM5Zm1sUTZoZjYzNjAwNU5WdTNFQkgyNEp0YTd1NFQzQmxia0ZKRzJ3MC1lRDROcmh2Q3h3T2lZekxRVGRTdVJOcGMyeWtXTHhfV0prQXJoaUVUXzB5bTB0RjdadzJqM3R4ODFjSjJhVzFQREExd0E=
